src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\LikeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LikeRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToMany(targetEntity: Category::class)]
    private Collection $category;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): static
    {
        if (! $this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\BookReadRepository;
use App\Repository\BookRepository;
use App\Repository\CategoryRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    private BookReadRepository $readBookRepository;

    // Inject the repository via the constructor
    public function __construct(private BookReadRepository $bookReadRepository,
        private Security $security,
        private BookRepository $bookRepository,
        private UserRepository $userRepository,
        private readonly CategoryRepository $categoryRepository)
    {
    }

    #[Route('/', name: 'app.home')]
    public function index(): Response
    {
        $user = $this->security->getUser();
        if (! $user) {
            return $this->redirectToRoute('app_login');
        }
        $userId = $user->getId();
        $user = $this->userRepository->find($userId);

        $booksRead = $this->bookReadRepository->findAllDetailsByUserId($user);
        $booksReading = $this->bookReadRepository->findAllByUserId($user, false);
        $books = $this->bookRepository->findAll();

        $radarData = $this->categoryRepository->getCategoriesWithBookReadCountByUserId($userId);

        return $this->render('pages/home.html.twig', [
            'books' => $books,
            'booksRead' => $booksRead,
            'booksReading' => $booksReading,
            'radarData' => json_encode($radarData),
            'name' => 'Accueil',
            'user' => $user->getUserIdentifier(),
        ]);
    }
}

templates/components/home/booksRead.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures terminées
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#read-books-table" placeholder="Rechercher" value="" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="read-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Catégorie</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Note</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in booksRead %}
                        <tr class="book-row">
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                       href="#"
                                       data-modal-toggle="#book_modal"
                                       data-id="{{ book.ID }}"
                                       data-book="{{ book.bookName }}"
                                       data-description="{{ book.description }}"
                                       data-rating="{{ book.rating }}"
                                       data-checked="{{ book.is_read }}">
                                        {{ book.bookName }}
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                        {{ book.description }}
                                    </span>
                                </div>
                            </td>
                            <td>{{ book.categoryName }}</td>
                            <td>
                                <div class="rating flex items-center mb-4">
                                    {% set fullStars = book.rating %}
                                    {% set emptyStars = 5 - fullStars %}

                                    {% if fullStars > 0 %}
                                        {% for i in range(1, fullStars) %}
                                            <div class="rating-label checked">
                                                <i class="rating-on ki-solid ki-star text-yellow-500"></i>
                                            </div>
                                        {% endfor %}
                                    {% endif %}

                                    {% if emptyStars > 0 %}
                                        {% for i in range(1, emptyStars) %}
                                            <div class="rating-label">
                                                <i class="rating-off ki-outline ki-star text-gray-300"></i>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-2 order-2 md:order-1">
                    Show
                    <select class="select select-sm w-16"
                            data-datatable-size="true" name="perpage">
                    </select>
                    per page
                </div>
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/booksReading.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures en cours
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <label>
                <input data-datatable-search="#current-books-table" placeholder="Rechercher" value="" type="text"/>
            </label>
        </div>
    </div>
    <div class="card-body">
        <div id="current-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table  class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="max-w-[135px] text-end">
                            <span class="sort">
                                <span class="sort-label">Modifié le</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookReading in booksReading %}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                       href="#"
                                       data-modal-toggle="#book_modal"
                                       data-id="{{ bookReading.ID }}"
                                       data-book="{{ bookReading.bookName }}"
                                       data-description="{{ bookReading.description }}"
                                       data-rating="{{ bookReading.rating }}"
                                       data-checked="{{ bookReading.is_read }}">
                                        {{ bookReading.bookName }}
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                        {{ bookReading.description }}
                                </span>
                                </div>
                            </td>
                            <td class="text-end">
                                {{ bookReading.updatedAt|date('d/m/Y à H:i') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/radarChart.html.twig
<div class="card h-full">
    <div class="card-header">
        <h3 class="card-title">
            Répartition de mes lectures
        </h3>
    </div>
    <div class="card-body flex flex-col gap-5">
        <div id="radar-chart"></div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

<script>
    var data = {{ radarData|raw }};
    const count = data.map((item) => (item.book_read_count));
    const categories = data.map((item) => (item.category_name));
    var options = {
        series: [{
            name: 'Nombre de livre lu',
            data: count,
        }],
        chart: {
            height: 350,
            type: 'radar',
        },
        dataLabels: {
            enabled: true
        },
        plotOptions: {
            radar: {
                size: 100,
                polygons: {
                    strokeColors: '#e9e9e9',
                    fill: {
                        colors: ['#f8f8f8', '#fff']
                    }
                }
            }
        },
        title: {
            text: 'Nombre de livre lu par catégorie'
        },
        colors: ['#FF4560'],
        markers: {
            size: 4,
            colors: ['#fff'],
            strokeColor: '#FF4560',
            strokeWidth: 2,
        },
        tooltip: {
            y: {
                formatter: function (val) {
                    return val
                }
            }
        },
        yaxis: {
            labels: {
                formatter: function(val, i) {
                    if (i % 2 === 0) {
                        return val
                    } else {
                        return ''
                    }
                }
            }
        },
        xaxis: {
            categories: categories
        }
    };

    var chart = new ApexCharts(document.querySelector("#radar-chart"), options);
    chart.render();

    function updateChart(category) {
        const index = categories.indexOf(category);
        if (index !== -1) {
            count[index] += 1;
            chart.destroy();
            chart = new ApexCharts(document.querySelector("#radar-chart"), {
                ...options,
                series: [{
                    name: 'Nombre de livre lu',
                    data: count,
                }]
            });
            chart.render();
        }
    }

    function removeChart(category) {
        const index = categories.indexOf(category);
        if (index !== -1) {
            count[index] -= 1;
            chart.destroy();
            chart = new ApexCharts(document.querySelector("#radar-chart"), {
                ...options,
                series: [{
                    name: 'Nombre de livre lu',
                    data: count,
                }]
            });
            chart.render();
        }
    }
</script>